add: admin panel, adding posts and their manager
grupacosmo/cosmo-page-frontend pull request #4
Opened 2024-03-18 14:07 UTC by Michal-Piotrkowski

project, achievements management + adding new ones tbd.

2024-03-19 15:12 UTC, tnt120 requested changes

2024-03-19 18:23 UTC, zaba51 commented on src/app/modules/admin/components/post/post.component.ts
> +  manager = this.service;
Or you can use injection with protected keyword instead of private

2024-03-19 18:30 UTC, zaba51 commented on src/app/modules/admin/pages/postComponents/add-post/add-post.component.scss
> +.InputContainer{
Dont use PascalCase

2024-03-19 19:04 UTC, zaba51 requested changes

2024-04-06 14:38 UTC, zaba51 approved these changes

2024-04-06 14:39 UTC, merged